// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd2bm__Dd_Lo_POhj6fIJJHm2s8g7sGh4',
    appId: '1:854179829182:web:91a8d7e470e790c5a7d5ef',
    messagingSenderId: '854179829182',
    projectId: 'mada-b82a9',
    authDomain: 'mada-b82a9.firebaseapp.com',
    storageBucket: 'mada-b82a9.firebasestorage.app',
    measurementId: 'G-DGMV3C9X5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeoOUT8920a_Jz5X-TvBCW3cAnYjmgU0s',
    appId: '1:854179829182:android:d05b2349196d7ceca7d5ef',
    messagingSenderId: '854179829182',
    projectId: 'mada-b82a9',
    storageBucket: 'mada-b82a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNQvXsq-8iewrZ42_jlf2SPBqAuYGqC4A',
    appId: '1:854179829182:ios:b6799afa627c2a32a7d5ef',
    messagingSenderId: '854179829182',
    projectId: 'mada-b82a9',
    storageBucket: 'mada-b82a9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNQvXsq-8iewrZ42_jlf2SPBqAuYGqC4A',
    appId: '1:854179829182:ios:b6799afa627c2a32a7d5ef',
    messagingSenderId: '854179829182',
    projectId: 'mada-b82a9',
    storageBucket: 'mada-b82a9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd2bm__Dd_Lo_POhj6fIJJHm2s8g7sGh4',
    appId: '1:854179829182:web:dfc477d7e4527d6ea7d5ef',
    messagingSenderId: '854179829182',
    projectId: 'mada-b82a9',
    authDomain: 'mada-b82a9.firebaseapp.com',
    storageBucket: 'mada-b82a9.firebasestorage.app',
    measurementId: 'G-YLZW5VSCBF',
  );
}
